/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package View.Modals;

import BusinessEntity.ClienteBE;
import BusinessEntity.MaestroDetalleBE;
import BusinessEntity.TarifaBE;
import BusinessEntity.VehiculoBE;
import BusinessEntity.ZonaParkingBE;
import BusinessLogic.ClienteBL;
import BusinessLogic.EstacionamientoBL;
import BusinessLogic.MaestroDetalleBL;
import BusinessLogic.TarifaBL;
import BusinessLogic.VehiculoBL;
import BusinessLogic.ZonaParkingBL;
import DTOs.EstacionamientoCrearDTO;
import Enums.TablasEnum;

import java.util.List;
import java.util.Optional;
import javax.swing.JOptionPane;

/**
 *
 * @author Royss
 */
public class ModalEstacionamiento extends javax.swing.JDialog {

    private MaestroDetalleBL maestroDetalleBL;
    private ZonaParkingBL zonaParkingBL;
    private ClienteBL clienteBL;
    private VehiculoBL vehiculoBL;
    private TarifaBL tarifaBL;
    private EstacionamientoBL estacionamientoBL;

    private List<MaestroDetalleBE> tipoDocumentos;
    private List<MaestroDetalleBE> tipoVehiculos;
    private List<ZonaParkingBE> zonasParking;
    private List<TarifaBE> tarifas;

    private TarifaBE tarifa;
    private MaestroDetalleBE tipoVehiculo;
    private MaestroDetalleBE tipoDocumento;
    private ZonaParkingBE zonaParking;
    private ClienteBE cliente;
    private VehiculoBE vehiculo;

    public ModalEstacionamiento(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        deshabilitarPorDefecto();
        habilitarComponentesClientes(true);
        habilitarComponentesVehiculo(false);

        maestroDetalleBL = new MaestroDetalleBL();
        zonaParkingBL = new ZonaParkingBL();
        clienteBL = new ClienteBL();
        vehiculoBL = new VehiculoBL();
        tarifaBL = new TarifaBL();
        estacionamientoBL = new EstacionamientoBL();

        cargarTipoDocumento();
        cargarTipoVehiculo();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtNumeroDocumento = new javax.swing.JTextField();
        cboTipoVehiculo = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        txtPrecio = new javax.swing.JTextField();
        btnCancelar = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();
        btnBuscarCliente = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        txtCliente = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtAdicional = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtCantidad = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtTotalEstimado = new javax.swing.JTextField();
        cboTipoDocumento = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtPlaca = new javax.swing.JTextField();
        btnBuscarPlaca = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        cboTarifa = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        txtMarca = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        txtModelo = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        txtColor = new javax.swing.JTextField();
        cboZonaParking = new javax.swing.JComboBox<>();
        jLabel15 = new javax.swing.JLabel();
        txtApellidos = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        lblTitulo.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblTitulo.setText("Nuevo Estacionamiento");

        jLabel1.setText("Numero Documento");

        txtNumeroDocumento.setName("txtUsuario"); // NOI18N

        cboTipoVehiculo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cboTipoVehiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboTipoVehiculoActionPerformed(evt);
            }
        });

        jLabel5.setText("Tipo Vehiculo");

        txtPrecio.setName("txtUsuario"); // NOI18N
        txtPrecio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPrecioActionPerformed(evt);
            }
        });

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        btnBuscarCliente.setText("Buscar");
        btnBuscarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarClienteActionPerformed(evt);
            }
        });

        jLabel6.setText("Nombres");

        txtCliente.setName("txtUsuario"); // NOI18N

        jLabel7.setText("Precio");

        jLabel8.setText("Precio Adicional");

        txtAdicional.setName("txtUsuario"); // NOI18N
        txtAdicional.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAdicionalActionPerformed(evt);
            }
        });
        txtAdicional.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtAdicionalKeyTyped(evt);
            }
        });

        jLabel9.setText("Cantidad");

        txtCantidad.setName("txtUsuario"); // NOI18N
        txtCantidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCantidadActionPerformed(evt);
            }
        });
        txtCantidad.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCantidadKeyTyped(evt);
            }
        });

        jLabel10.setText("Total Estimado");

        txtTotalEstimado.setName("txtUsuario"); // NOI18N
        txtTotalEstimado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTotalEstimadoActionPerformed(evt);
            }
        });

        cboTipoDocumento.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cboTipoDocumento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboTipoDocumentoActionPerformed(evt);
            }
        });

        jLabel11.setText("Tipo Documento");

        jLabel2.setText("Placa");

        txtPlaca.setName("txtUsuario"); // NOI18N

        btnBuscarPlaca.setText("Buscar");
        btnBuscarPlaca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarPlacaActionPerformed(evt);
            }
        });

        jLabel12.setText("Tarifa");

        cboTarifa.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cboTarifa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboTarifaActionPerformed(evt);
            }
        });

        jLabel4.setText("Marca");

        txtMarca.setName("txtUsuario"); // NOI18N

        jLabel13.setText("Modelo");

        txtModelo.setName("txtUsuario"); // NOI18N

        jLabel14.setText("Color");

        txtColor.setName("txtUsuario"); // NOI18N

        cboZonaParking.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cboZonaParking.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboZonaParkingActionPerformed(evt);
            }
        });

        jLabel15.setText("Zona Parking");

        txtApellidos.setName("txtUsuario"); // NOI18N

        jLabel16.setText("Apellidos");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblTitulo)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(txtPlaca, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnBuscarPlaca, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel10)
                            .addComponent(txtTotalEstimado, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jSeparator2)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(cboTipoVehiculo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel4)
                                            .addComponent(txtMarca, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtModelo, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel13))
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel14)
                                            .addComponent(txtColor, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                .addComponent(txtPrecio)
                                                .addComponent(cboTarifa, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.LEADING))
                                            .addComponent(jLabel7))
                                        .addGap(22, 22, 22)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(cboZonaParking, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel15)
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                .addGroup(jPanel1Layout.createSequentialGroup()
                                                    .addComponent(btnCancelar)
                                                    .addGap(18, 18, 18)
                                                    .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jLabel8)
                                                        .addComponent(txtAdicional, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                    .addGap(18, 18, 18)
                                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jLabel9)
                                                        .addComponent(txtCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                                .addGap(0, 14, Short.MAX_VALUE)))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel6)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addComponent(txtCliente))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtApellidos, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel16)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cboTipoDocumento, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel11))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(txtNumeroDocumento, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(btnBuscarCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                        .addGap(25, 25, 25))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(lblTitulo)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cboTipoDocumento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtNumeroDocumento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnBuscarCliente))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel16)
                        .addGap(28, 28, 28))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtApellidos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(7, 7, 7)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPlaca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscarPlaca))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtMarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel13)
                            .addGap(28, 28, 28))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel14)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txtColor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtModelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cboTipoVehiculo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cboTarifa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel15)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cboZonaParking, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtAdicional, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtTotalEstimado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancelar)
                    .addComponent(btnGuardar))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
       this.dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed

        try {
            cliente = new ClienteBE();
            cliente.setDocumento(txtNumeroDocumento.getText());
            cliente.setNombre(txtCliente.getText());
            cliente.setApellidos(txtApellidos.getText());
            cliente.setTipoDocumento(tipoDocumento.getId());

            vehiculo = new VehiculoBE();
            vehiculo.setPlaca(txtPlaca.getText());
            vehiculo.setMarca(txtMarca.getText());
            vehiculo.setModelo(txtModelo.getText());
            vehiculo.setColor(txtColor.getText());
            vehiculo.setIdTipoVehiculo(tipoVehiculo.getId());

            EstacionamientoCrearDTO estacionamientoCrearDTO = new EstacionamientoCrearDTO(
                    cliente,
                    vehiculo,
                    tarifa,
                    zonaParking
            );

            boolean flag = estacionamientoBL.guardar(estacionamientoCrearDTO);
            if (!flag) {
                JOptionPane.showMessageDialog(null, "No se ha podido guardar el estacionamiento", "Mensaje", JOptionPane.INFORMATION_MESSAGE);
                return;
            }

            JOptionPane.showMessageDialog(null, "Estacionamiento guardado", "Mensaje", JOptionPane.INFORMATION_MESSAGE);

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Ha ocurrido un error", "Mensaje", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void txtPrecioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPrecioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPrecioActionPerformed

    private void txtAdicionalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAdicionalActionPerformed
        calcularTotalEstimado();
    }//GEN-LAST:event_txtAdicionalActionPerformed

    private void txtTotalEstimadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTotalEstimadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTotalEstimadoActionPerformed

    private void btnBuscarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarClienteActionPerformed

        String tipoDocumentoValor = (String) cboTipoDocumento.getSelectedItem();
        String documentoValor = txtNumeroDocumento.getText();

        txtCliente.setText("");
        txtApellidos.setText("");

        if (documentoValor.isBlank() || documentoValor.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Debe ingresar el numero Documento", "Mensaje", JOptionPane.INFORMATION_MESSAGE);
            return;
        }

        Optional<MaestroDetalleBE> tipoDocumento = tipoDocumentos.stream().filter(td -> td.getValor().equals(tipoDocumentoValor))
                .findFirst();

        try {
            cliente = this.clienteBL.buscarCliente(tipoDocumento.get().getId(), documentoValor);
            if (cliente == null) {
                JOptionPane.showMessageDialog(null, "No se ha encontrado al cliente", "Mensaje", JOptionPane.INFORMATION_MESSAGE);
                habilitarComponentesClientesPorTipoDocumento(true);
                return;
            }

            habilitarComponentesClientesPorTipoDocumento(false);
            txtCliente.setText(cliente.getNombre());
            txtApellidos.setText(cliente.getApellidos());
            habilitarComponentesVehiculo(true);

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Ha ocurrido un error", "Mensaje", JOptionPane.ERROR_MESSAGE);
        }

        return;
    }//GEN-LAST:event_btnBuscarClienteActionPerformed

    private void btnBuscarPlacaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarPlacaActionPerformed
        String placaValor = txtPlaca.getText();

        txtMarca.setText("");
        txtModelo.setText("");
        txtColor.setText("");

        if (placaValor.isBlank() || placaValor.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Debe ingresar la Placa", "Mensaje", JOptionPane.INFORMATION_MESSAGE);
            return;
        }

        try {
            vehiculo = this.vehiculoBL.buscarVehiculo(placaValor);
            if (vehiculo == null) {
                JOptionPane.showMessageDialog(null, "No se ha encontrado el vehiculo", "Mensaje", JOptionPane.INFORMATION_MESSAGE);
                habilitarComponentesClientesPorPlaca(true);
                return;
            }

            habilitarComponentesClientesPorPlaca(false);
            txtMarca.setText(vehiculo.getMarca());
            txtModelo.setText(vehiculo.getModelo());
            txtColor.setText(vehiculo.getColor());

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Ha ocurrido un error", "Mensaje", JOptionPane.ERROR_MESSAGE);
        }

        return;
    }//GEN-LAST:event_btnBuscarPlacaActionPerformed

    private void cboTipoDocumentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboTipoDocumentoActionPerformed
        String tipoDocumentoValor = (String) cboTipoDocumento.getSelectedItem();

        if (tipoDocumentoValor == null) {
            return;
        }

        tipoDocumento = tipoDocumentos.stream().filter(tv -> tv.getValor().equals(tipoDocumentoValor)).findFirst().get();

        habilitarComponentesClientesPorTipoDocumento(false);
        habilitarComponentesVehiculo(false);

        limpiarComponentesCliente();
        limpiarComponentesVehiculo();
    }//GEN-LAST:event_cboTipoDocumentoActionPerformed

    private void cboTipoVehiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboTipoVehiculoActionPerformed
        String tipoVehiculoCValor = (String) cboTipoVehiculo.getSelectedItem();
        Optional<MaestroDetalleBE> tipoVehiculoOpt = tipoVehiculos.stream().filter(tv -> tv.getValor().equals(tipoVehiculoCValor)).findFirst();

        if (!tipoVehiculoOpt.isPresent()) {
            return;
        }

        tipoVehiculo = tipoVehiculoOpt.get();
        int idTipoVehiculo = tipoVehiculo.getId();

        cargarZonaParking(idTipoVehiculo);
        cargarTarifas(idTipoVehiculo);
    }//GEN-LAST:event_cboTipoVehiculoActionPerformed

    private void cboTarifaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboTarifaActionPerformed
        String tarifaValor = (String) cboTarifa.getSelectedItem();
        Optional<TarifaBE> tarifaOp = tarifas.stream().filter(t -> t.getNombre().equals(tarifaValor)).findFirst();

        if (!tarifaOp.isPresent()) {
            return;
        }

        tarifa = tarifaOp.get();

        if (tarifa != null) {
            txtPrecio.setText(String.valueOf(tarifa.getPrecioBase()));
        }
    }//GEN-LAST:event_cboTarifaActionPerformed

    private void txtCantidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCantidadActionPerformed
        calcularTotalEstimado();
    }//GEN-LAST:event_txtCantidadActionPerformed

    private void txtCantidadKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCantidadKeyTyped
        soloDigitos(evt);
    }//GEN-LAST:event_txtCantidadKeyTyped

    private void txtAdicionalKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAdicionalKeyTyped
        soloDigitos(evt);
    }//GEN-LAST:event_txtAdicionalKeyTyped

    private void cboZonaParkingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboZonaParkingActionPerformed
        String zonaParkingValor = (String) cboZonaParking.getSelectedItem();
        Optional<ZonaParkingBE> zonaParkingOpt = zonasParking.stream().filter(tv -> tv.getNombre().equals(zonaParkingValor)).findFirst();

        if (!zonaParkingOpt.isPresent()) {
            return;
        }

        zonaParking = zonaParkingOpt.get();
    }//GEN-LAST:event_cboZonaParkingActionPerformed

    private void soloDigitos(java.awt.event.KeyEvent evt) {
        char c = evt.getKeyChar();
        if (!Character.isDigit(c)) {
            evt.consume();
        }
    }

    private void calcularTotalEstimado() {

        if (tarifa == null) {
            return;
        }

        int cantidad = txtCantidad.getText().length() > 0 ? Integer.parseInt(txtCantidad.getText()) : 0;
        int adicional = txtAdicional.getText().length() > 0 ? Integer.parseInt(txtAdicional.getText()) : 0;
        double totalEstimado = (tarifa.getPrecioBase() * cantidad) + adicional;
        txtTotalEstimado.setText(String.valueOf(totalEstimado));
    }

    private void limpiarComponentesCliente() {
        txtCliente.setText("");
        txtApellidos.setText("");
        txtNumeroDocumento.setText("");
    }

    private void limpiarComponentesVehiculo() {
        txtMarca.setText("");
        txtModelo.setText("");
        txtColor.setText("");
        txtPlaca.setText("");
    }

    private void habilitarComponentesClientesPorTipoDocumento(Boolean flag) {
        txtCliente.setEnabled(flag);
        txtApellidos.setEnabled(flag);
    }

    private void habilitarComponentesClientesPorPlaca(Boolean flag) {
        txtMarca.setEnabled(flag);
        txtModelo.setEnabled(flag);
        txtColor.setEnabled(flag);
    }

    private void cargarTipoDocumento() {
        tipoDocumentos = this.maestroDetalleBL.GetAllMaestroDetalle(TablasEnum.TIPO_DOCUMENTO.getValor());

        cboTipoDocumento.removeAll();
        cboTipoDocumento.removeAllItems();
        for (MaestroDetalleBE td : tipoDocumentos) {
            cboTipoDocumento.addItem(td.getValor());
        }
    }

    private void cargarTipoVehiculo() {
        tipoVehiculos = this.maestroDetalleBL.GetAllMaestroDetalle(TablasEnum.TIPO_VEHICULO.getValor());

        cboTipoVehiculo.removeAll();
        cboTipoVehiculo.removeAllItems();
        for (MaestroDetalleBE td : tipoVehiculos) {
            cboTipoVehiculo.addItem(td.getValor());
        }
    }

    private void cargarZonaParking(int idTipoVehiculo) {
        zonasParking = zonaParkingBL.obtenerTodoPorTipoVehiculo(idTipoVehiculo);

        cboZonaParking.removeAll();
        cboZonaParking.removeAllItems();
        cboZonaParking.addItem("--Seleccione--");
        for (ZonaParkingBE td : zonasParking) {
            cboZonaParking.addItem(td.getNombre());
        }
    }

    private void cargarTarifas(int idTipoVehiculo) {
        tarifas = tarifaBL.obtenerTodoPorTipoVehiculo(idTipoVehiculo);

        cboTarifa.removeAll();
        cboTarifa.removeAllItems();
        cboTarifa.addItem("--Seleccione--");
        for (TarifaBE td : tarifas) {
            cboTarifa.addItem(td.getNombre());
        }
    }

    private void habilitarComponentesClientes(Boolean flag) {
        cboTipoDocumento.setEnabled(flag);
        txtNumeroDocumento.setEnabled(flag);
        btnBuscarCliente.setEnabled(flag);
    }

    private void habilitarComponentesVehiculo(Boolean flag) {
        txtPlaca.setEnabled(flag);
        btnBuscarPlaca.setEnabled(flag);
    }

    private void deshabilitarPorDefecto() {
        txtCliente.setEnabled(false);
        txtApellidos.setEnabled(false);
        txtMarca.setEnabled(false);
        txtModelo.setEnabled(false);
        txtColor.setEnabled(false);
        txtPrecio.setEnabled(false);
        txtTotalEstimado.setEnabled(false);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ModalEstacionamiento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ModalEstacionamiento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ModalEstacionamiento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ModalEstacionamiento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ModalEstacionamiento dialog = new ModalEstacionamiento(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscarCliente;
    private javax.swing.JButton btnBuscarPlaca;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JComboBox<String> cboTarifa;
    private javax.swing.JComboBox<String> cboTipoDocumento;
    private javax.swing.JComboBox<String> cboTipoVehiculo;
    private javax.swing.JComboBox<String> cboZonaParking;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JTextField txtAdicional;
    private javax.swing.JTextField txtApellidos;
    private javax.swing.JTextField txtCantidad;
    private javax.swing.JTextField txtCliente;
    private javax.swing.JTextField txtColor;
    private javax.swing.JTextField txtMarca;
    private javax.swing.JTextField txtModelo;
    private javax.swing.JTextField txtNumeroDocumento;
    private javax.swing.JTextField txtPlaca;
    private javax.swing.JTextField txtPrecio;
    private javax.swing.JTextField txtTotalEstimado;
    // End of variables declaration//GEN-END:variables
}
